export enum EventKey {
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  START_GAME = 'START_GAME',
  END_GAME = 'END_GAME',
  PLAY_AGAIN = 'PLAY_AGAIN',

  UPDATE_MEMBERS = 'UPDATE_MEMBERS',

  REFRESH_PLAYERS = 'REFRESH_PLAYERS',
  SET_ROOM_HOST = 'SET_ROOM_HOST',

  SPIN = 'SPIN',
  PLAYER_SELECTED = 'PLAYER_SELECTED',

  PICK_PROMPT = 'PICK_PROMPT',
  TRUTH_PROMPT_SELECTED = 'TRUTH_PROMPT_SELECTED',
  TRICK_PROMPT_SELECTED = 'TRICK_PROMPT_SELECTED',
  END_TURN = 'END_TURN',
  HIDE_PLAYER_SELECTED_POPUP = 'HIDE_PLAYER_SELECTED_POPUP',
  NEXT_TURN = "NEXT_TURN",
}
